/**
 * Barrel for career-platform Drizzle table schemas.
 *
 * `auth.ts` is machine-generated by the Better Auth CLI (RR-005):
 *   bun run career:auth-generate
 * Never hand-edit it — regenerate when the auth config changes.
 *
 * Domain tables (candidate profiles RR-008, assignments RR-011, …) are added
 * as `src/schema/<domain>.ts` and re-exported here; `drizzle.config.ts` globs
 * this directory, so no config change is needed when a domain is added.
 */
export * from './auth';
export * from './candidate-profile';
export * from './audit';
export * from './assistant';
export * from './resume';
export * from './job';
