/**
 * Re-exports the shared API contracts for use across career-web's ViewModels
 * (hooks) and Models (lib). The web app consumes types + Zod schemas from
 * `@career/contracts`; it must never import `@career/db`.
 */
export {
  roleSchema,
  applicationStatusSchema,
  workOrderStatusSchema,
  assignmentPermissionSchema,
  paginationQuerySchema,
  candidateProfileInputSchema,
  candidateProfileSchema,
  remotePreferenceSchema,
  createResumeInputSchema,
  resumeSchema,
  resumeContentTypeSchema,
  resumeStatusSchema,
  RESUME_MAX_BYTES,
  jobSchema,
  jobQuerySchema,
  jobInputSchema,
  jobUpdateSchema,
  jobStatusSchema,
  jobRemoteTypeSchema,
  employmentTypeSchema,
  type Role,
  type ApplicationStatus,
  type WorkOrderStatus,
  type AssignmentPermission,
  type PaginationQuery,
  type PaginationMeta,
  type ValidationError,
  type SuccessResponse,
  type PaginatedResponse,
  type CandidateProfile,
  type CandidateProfileInput,
  type RemotePreference,
  type Resume,
  type ResumeStatus,
  type ResumeContentType,
  type CreateResumeInput,
  type CreateResumeResponse,
  type ResumeDownload,
  type ResumeList,
  type UploadTicket,
  type Job,
  type JobList,
  type JobQuery,
  type JobInput,
  type JobUpdate,
  type JobStatus,
  type JobRemoteType,
  type EmploymentType,
} from '@career/contracts';
